[2025-01-13T14:16:38.552+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_bq manual__2025-01-13T14:10:45.278837+00:00 [queued]>
[2025-01-13T14:16:38.630+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_bq manual__2025-01-13T14:10:45.278837+00:00 [queued]>
[2025-01-13T14:16:38.630+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-13T14:16:38.765+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_transaction_to_bq> on 2025-01-13 14:10:45.278837+00:00
[2025-01-13T14:16:38.834+0000] {standard_task_runner.py:57} INFO - Started process 2155 to run task
[2025-01-13T14:16:38.899+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_transaction_to_bq', 'manual__2025-01-13T14:10:45.278837+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpb2nc8wgb']
[2025-01-13T14:16:38.963+0000] {standard_task_runner.py:85} INFO - Job 245: Subtask load_to_gcs_bq.load_transaction_to_bq
[2025-01-13T14:16:39.311+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_bq manual__2025-01-13T14:10:45.278837+00:00 [running]> on host ab4e86dc450e
[2025-01-13T14:16:39.915+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_transaction_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T14:10:45.278837+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T14:10:45.278837+00:00'
[2025-01-13T14:16:39.933+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T14:16:39.935+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T14:16:39.937+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T14:16:39.938+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-13T14:16:40.427+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_raw', 'tableId': 'src_transactions'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/transactions/2025-01-13/transactions.parquet'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'transaction_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'transaction_id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'account_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'customer_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'product_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'location_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'date_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'transaction_type', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'amount', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'status', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'ingestion_timestamp', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}]}}}
[2025-01-13T14:16:40.444+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_transaction_to_bq_2025_01_13T14_10_45_278837_00_00_a7afda61af2f7de7d74645180af2a826
[2025-01-13T14:16:40.916+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_transactions. Cannot add fields (field: transaction_key)
[2025-01-13T14:16:40.959+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_transaction_to_bq, execution_date=20250113T141045, start_date=20250113T141638, end_date=20250113T141640
[2025-01-13T14:16:41.042+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 245 for task load_to_gcs_bq.load_transaction_to_bq (400 Provided Schema does not match Table finflow-analytics-production:finflow_raw.src_transactions. Cannot add fields (field: transaction_key); 2155)
[2025-01-13T14:16:41.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T14:16:41.251+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
