[2025-01-16T16:50:04.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_temp manual__2025-01-16T16:49:01.042510+00:00 [queued]>
[2025-01-16T16:50:04.900+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_temp manual__2025-01-16T16:49:01.042510+00:00 [queued]>
[2025-01-16T16:50:04.901+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T16:50:05.376+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_to_gcs_bq.load_transaction_to_temp> on 2025-01-16 16:49:01.042510+00:00
[2025-01-16T16:50:05.567+0000] {standard_task_runner.py:57} INFO - Started process 1459 to run task
[2025-01-16T16:50:05.638+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.load_transaction_to_temp', 'manual__2025-01-16T16:49:01.042510+00:00', '--job-id', '2008', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmp8fn80942']
[2025-01-16T16:50:05.780+0000] {standard_task_runner.py:85} INFO - Job 2008: Subtask load_to_gcs_bq.load_transaction_to_temp
[2025-01-16T16:50:06.507+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.load_transaction_to_temp manual__2025-01-16T16:49:01.042510+00:00 [running]> on host e65a9a79c958
[2025-01-16T16:50:07.765+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.load_transaction_to_temp' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T16:49:01.042510+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T16:49:01.042510+00:00'
[2025-01-16T16:50:07.803+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T16:50:07.816+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T16:50:07.822+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T16:50:07.838+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2025-01-16T16:50:08.516+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': False, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'finflow-analytics-production', 'datasetId': 'finflow_data', 'tableId': 'src_transactions_temp'}, 'sourceFormat': 'PARQUET', 'sourceUris': ['gs://finflow-analytics-data/raw/transactions/2025-01-16/transactions.parquet'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': True, 'schema': {'fields': [{'name': 'transaction_id', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'account_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'customer_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'product_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'location_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'date_key', 'type': 'INTEGER', 'mode': 'REQUIRED'}, {'name': 'transaction_type', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'transaction_amount', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'fee_amount', 'type': 'FLOAT', 'mode': 'REQUIRED'}, {'name': 'transaction_status', 'type': 'STRING', 'mode': 'REQUIRED'}, {'name': 'created_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'updated_at', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}, {'name': 'ingestion_timestamp', 'type': 'TIMESTAMP', 'mode': 'REQUIRED'}]}}}
[2025-01-16T16:50:08.519+0000] {bigquery.py:1595} INFO - Inserting job ***_finflow_source_data_pipeline_load_to_gcs_bq_load_transaction_to_temp_2025_01_16T16_49_01_042510_00_00_b7efc2b163c14446fe49b6c60e02efc4
[2025-01-16T16:50:10.177+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 439, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: Invalid timestamp microseconds value 1737046173000000000 of logical type NONE; in column 'created_at' File: gs://finflow-analytics-data/raw/transactions/2025-01-16/transactions.parquet
[2025-01-16T16:50:10.200+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.load_transaction_to_temp, execution_date=20250116T164901, start_date=20250116T165004, end_date=20250116T165010
[2025-01-16T16:50:10.230+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2008 for task load_to_gcs_bq.load_transaction_to_temp (400 Error while reading data, error message: Invalid timestamp microseconds value 1737046173000000000 of logical type NONE; in column 'created_at' File: gs://finflow-analytics-data/raw/transactions/2025-01-16/transactions.parquet; 1459)
[2025-01-16T16:50:10.268+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T16:50:10.379+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
