[2025-01-13T20:54:21.379+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.merge_account_to_main manual__2025-01-13T20:52:53.399336+00:00 [queued]>
[2025-01-13T20:54:21.542+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.merge_account_to_main manual__2025-01-13T20:52:53.399336+00:00 [queued]>
[2025-01-13T20:54:21.550+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-13T20:54:21.854+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): load_to_gcs_bq.merge_account_to_main> on 2025-01-13 20:52:53.399336+00:00
[2025-01-13T20:54:21.896+0000] {standard_task_runner.py:57} INFO - Started process 18188 to run task
[2025-01-13T20:54:21.949+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.merge_account_to_main', 'manual__2025-01-13T20:52:53.399336+00:00', '--job-id', '1025', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmp3zj7_qmu']
[2025-01-13T20:54:22.027+0000] {standard_task_runner.py:85} INFO - Job 1025: Subtask load_to_gcs_bq.merge_account_to_main
[2025-01-13T20:54:22.469+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.merge_account_to_main manual__2025-01-13T20:52:53.399336+00:00 [running]> on host ab4e86dc450e
[2025-01-13T20:54:23.330+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.merge_account_to_main' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T20:52:53.399336+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T20:52:53.399336+00:00'
[2025-01-13T20:54:23.334+0000] {bigquery.py:1241} INFO - Executing: 
-- Create the target table if it doesn't exist
CREATE TABLE IF NOT EXISTS `finflow-analytics-production.finflow_data.src_accounts` (
    account_key INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    customer_key INTEGER NOT NULL,
    product_key INTEGER NOT NULL,
    account_type STRING NOT NULL,
    account_status STRING NOT NULL,
    initial_deposit FLOAT64 NOT NULL,
    minimum_balance FLOAT64 NOT NULL,
    balance FLOAT64 NOT NULL,
    credit_limit FLOAT64 NOT NULL,
    opened_date DATE NOT NULL,
    closed_date DATE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    ingestion_timestamp TIMESTAMP NOT NULL
);

-- Perform the merge operation
MERGE `finflow-analytics-production.finflow_data.src_accounts` T
USING `finflow-analytics-production.finflow_data.src_accounts_temp` S
ON T.account_key = S.account_key
WHEN MATCHED THEN
    UPDATE SET
        T.account_id = S.account_id,
        T.customer_key = S.customer_key,
        T.product_key = S.product_key,
        T.account_type = S.account_type,
        T.account_status = S.account_status,
        T.initial_deposit = S.initial_deposit,
        T.minimum_balance = S.minimum_balance,
        T.balance = S.balance,
        T.credit_limit = S.credit_limit,
        T.opened_date = S.opened_date,
        T.closed_date = S.closed_date,
        T.created_at = S.created_at,
        T.updated_at = S.updated_at,
        T.ingestion_timestamp = S.ingestion_timestamp
WHEN NOT MATCHED THEN
    INSERT (account_key, account_id, customer_key, product_key, account_type, account_status, initial_deposit, minimum_balance, balance, credit_limit, opened_date, closed_date, created_at, updated_at, ingestion_timestamp)
    VALUES (S.account_key, S.account_id, S.customer_key, S.product_key, S.account_type, S.account_status, S.initial_deposit, S.minimum_balance, S.balance, S.credit_limit, S.opened_date, S.closed_date, S.created_at, S.updated_at, S.ingestion_timestamp)
[2025-01-13T20:54:23.337+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T20:54:23.351+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-13T20:54:23.355+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-13T20:54:23.375+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108: AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  warnings.warn(

[2025-01-13T20:54:24.092+0000] {bigquery.py:1595} INFO - Inserting job ***_1736801664091354_377428c4827feb8411bec8f6f5086210
[2025-01-13T20:54:26.270+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1249, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2241, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1601, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1580, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1570, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Query error: Value of type INT64 cannot be assigned to T.closed_date, which has type DATE at [37:25]

Location: us-central1
Job ID: airflow_1736801664091354_377428c4827feb8411bec8f6f5086210

[2025-01-13T20:54:26.356+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.merge_account_to_main, execution_date=20250113T205253, start_date=20250113T205421, end_date=20250113T205426
[2025-01-13T20:54:26.448+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1025 for task load_to_gcs_bq.merge_account_to_main (400 Query error: Value of type INT64 cannot be assigned to T.closed_date, which has type DATE at [37:25]

Location: us-central1
Job ID: airflow_1736801664091354_377428c4827feb8411bec8f6f5086210
; 18188)
[2025-01-13T20:54:26.519+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T20:54:26.677+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
