[2025-01-16T17:06:34.963+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.transform_date_timestamps manual__2025-01-16T17:05:02.979191+00:00 [queued]>
[2025-01-16T17:06:35.109+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.transform_date_timestamps manual__2025-01-16T17:05:02.979191+00:00 [queued]>
[2025-01-16T17:06:35.117+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-16T17:06:35.300+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): load_to_gcs_bq.transform_date_timestamps> on 2025-01-16 17:05:02.979191+00:00
[2025-01-16T17:06:35.402+0000] {standard_task_runner.py:57} INFO - Started process 2207 to run task
[2025-01-16T17:06:35.464+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'finflow_source_data_pipeline', 'load_to_gcs_bq.transform_date_timestamps', 'manual__2025-01-16T17:05:02.979191+00:00', '--job-id', '2077', '--raw', '--subdir', 'DAGS_FOLDER/finflow.py', '--cfg-path', '/tmp/tmpl1c_rcb7']
[2025-01-16T17:06:35.505+0000] {standard_task_runner.py:85} INFO - Job 2077: Subtask load_to_gcs_bq.transform_date_timestamps
[2025-01-16T17:06:36.103+0000] {task_command.py:416} INFO - Running <TaskInstance: finflow_source_data_pipeline.load_to_gcs_bq.transform_date_timestamps manual__2025-01-16T17:05:02.979191+00:00 [running]> on host e65a9a79c958
[2025-01-16T17:06:37.036+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='finflow_source_data_pipeline' AIRFLOW_CTX_TASK_ID='load_to_gcs_bq.transform_date_timestamps' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T17:05:02.979191+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T17:05:02.979191+00:00'
[2025-01-16T17:06:37.042+0000] {bigquery.py:1241} INFO - Executing: 
                    CREATE OR REPLACE TABLE `finflow-analytics-production.finflow_data.src_dates_temp` AS
                    SELECT 
                        date_key,
                        full_date,
                        year,
                        quarter,
                        month,
                        day,
                        day_of_week,
                        is_weekend,
                        is_holiday,
                        fiscal_year,
                        TIMESTAMP_SECONDS(CAST(created_at AS INT64)) as created_at,
                        TIMESTAMP_SECONDS(CAST(updated_at AS INT64)) as updated_at,
                        TIMESTAMP_SECONDS(CAST(ingestion_timestamp AS INT64)) as ingestion_timestamp
                    FROM `finflow-analytics-production.finflow_data.src_dates_temp`
                    
[2025-01-16T17:06:37.062+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-16T17:06:37.075+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-01-16T17:06:37.082+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-01-16T17:06:37.119+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2108: AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  warnings.warn(

[2025-01-16T17:06:38.053+0000] {bigquery.py:1595} INFO - Inserting job ***_1737047198051825_14a4c6ce6dbb326976c92ea1bd86927b
[2025-01-16T17:06:39.234+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1249, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2241, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1601, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1580, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1570, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Invalid cast from TIMESTAMP to INT64 at [14:48]

Location: us-central1
Job ID: airflow_1737047198051825_14a4c6ce6dbb326976c92ea1bd86927b

[2025-01-16T17:06:39.368+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=finflow_source_data_pipeline, task_id=load_to_gcs_bq.transform_date_timestamps, execution_date=20250116T170502, start_date=20250116T170634, end_date=20250116T170639
[2025-01-16T17:06:40.122+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2077 for task load_to_gcs_bq.transform_date_timestamps (400 Invalid cast from TIMESTAMP to INT64 at [14:48]

Location: us-central1
Job ID: airflow_1737047198051825_14a4c6ce6dbb326976c92ea1bd86927b
; 2207)
[2025-01-16T17:06:40.340+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T17:06:40.819+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
